services:
  - type: web
    name: finance-tracker-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
